/** Nigerian banks — commercial banks plus the fintech/microfinance banks
 * commonly used for transfers. Used to power a searchable picker instead of
 * asking reps to free-type a bank name at checkout settings. */
export const NIGERIAN_BANKS: string[] = [
  "Access Bank",
  "Citibank Nigeria",
  "Ecobank Nigeria",
  "Fidelity Bank",
  "First Bank of Nigeria",
  "First City Monument Bank (FCMB)",
  "Globus Bank",
  "Guaranty Trust Bank (GTBank)",
  "Heritage Bank",
  "Jaiz Bank",
  "Keystone Bank",
  "Lotus Bank",
  "Optimus Bank",
  "Parallex Bank",
  "Polaris Bank",
  "Premium Trust Bank",
  "Providus Bank",
  "Signature Bank",
  "Stanbic IBTC Bank",
  "Standard Chartered Bank",
  "Sterling Bank",
  "SunTrust Bank",
  "TAJ Bank",
  "Titan Trust Bank",
  "Union Bank of Nigeria",
  "United Bank for Africa (UBA)",
  "Unity Bank",
  "Wema Bank",
  "Zenith Bank",
  // merchant / non-interest / development banks
  "Coronation Merchant Bank",
  "FSDH Merchant Bank",
  "Nova Merchant Bank",
  "Rand Merchant Bank",
  "FBNQuest Merchant Bank",
  "Greenwich Merchant Bank",
  "Bank of Industry (BOI)",
  "Bank of Agriculture (BOA)",
  // digital banks / fintechs commonly used for transfers
  "Kuda Bank",
  "Opay",
  "PalmPay",
  "Moniepoint MFB",
  "VFD Microfinance Bank",
  "Carbon",
  "Sparkle Bank",
  "Mint Finex MFB",
  "Rubies Bank",
];
